# Generated by Django 2.2.1 on 2022-07-18 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Sedes',
        ),
    ]
