# Generated by Django 2.2.1 on 2022-07-27 17:04

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificado', models.DateTimeField(auto_now=True, null=True)),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(max_length=500)),
                ('descripcion', ckeditor.fields.RichTextField(blank=True, max_length=15000, null=True)),
                ('archivo_audio', models.FileField(blank=True, default='', null=True, upload_to='audio/', verbose_name='Archivo Audio')),
                ('urlvideo', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='URL Youtube')),
                ('vimeo_id', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('viral', models.BooleanField(default=False)),
                ('ultima_hora', models.BooleanField()),
                ('fecha_inicio_publicacion', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de inicio de publicación')),
                ('fecha_final_publicacion', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de finalización de publicación')),
                ('orden_destacado', models.IntegerField(choices=[(0, 'Principal'), (1, 'Destacado 1'), (2, 'Destacado 2'), (3, 'Destacado 3'), (4, 'General 4')], default=0)),
                ('imagen_destacado', models.FileField(blank=True, null=True, upload_to='imagenes/', verbose_name='Imagen Destacado')),
                ('video_destacado', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Video Destacado')),
                ('fuente', models.CharField(default='INRAI', help_text='Fuente noticia', max_length=50)),
                ('html', models.TextField(blank=True, default='', max_length=10000, null=True)),
                ('pdf', models.FileField(blank=True, default='', null=True, upload_to='pdf/', verbose_name='Archivo PDF')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('estado', models.IntegerField(choices=[(0, 'En aprobación'), (1, 'Devuelto para revisión'), (2, 'Rechazado'), (3, 'Aprobado'), (4, 'Publicado')], default=0)),
                ('autor', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subcategoria', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='catalogos.SubCategoria')),
            ],
            options={
                'verbose_name_plural': 'Noticias',
            },
        ),
        migrations.CreateModel(
            name='Sedes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificado', models.DateTimeField(auto_now=True, null=True)),
                ('sede', models.IntegerField(default=0)),
                ('nombre_sede', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Sedes',
            },
        ),
        migrations.CreateModel(
            name='Suscribir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificado', models.DateTimeField(auto_now=True, null=True)),
                ('email', models.CharField(help_text='eMail', max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Suscribirse',
            },
        ),
        migrations.CreateModel(
            name='Publicados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificado', models.DateTimeField(auto_now=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticias.Noticias')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='noticias.Sedes')),
            ],
            options={
                'verbose_name_plural': 'Publicados',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.FileField(default='', upload_to='fotos/', verbose_name='Archivo con Foto del Usuario')),
                ('sede', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='noticias.Sedes')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
