# Generated by Django 2.2.1 on 2022-07-27 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticias',
            name='video_destacado',
        ),
    ]
