# Generated by Django 2.2.1 on 2022-07-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='video_destacado',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Video Destacado'),
        ),
    ]
