# Generated by Django 2.2.1 on 2022-08-01 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_fotos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotos',
            name='subtitulo',
        ),
    ]
