# Generated by Django 2.2.1 on 2022-08-01 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_remove_fotos_subtitulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias_fotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificado', models.DateTimeField(auto_now=True, null=True)),
                ('nombre', models.CharField(help_text='Nombre de la categoría', max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorias Fotos',
            },
        ),
        migrations.AddField(
            model_name='fotos',
            name='categoria',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='noticias.Categorias_fotos'),
        ),
    ]
