# Generated by Django 2.2.1 on 2022-07-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_noticias_profile_sedes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscribir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificado', models.DateTimeField(auto_now=True, null=True)),
                ('email', models.CharField(help_text='eMail', max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Suscribirse',
            },
        ),
    ]
