# Generated by Django 2.2.1 on 2022-07-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0006_suscribir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticias',
            name='publicar_en',
        ),
        migrations.AlterField(
            model_name='noticias',
            name='subtitulo',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
